### ISSUE TITLE
wstool update

### ISSUE THREAD

**Issue by maxwu8416** [ethz-asl/waypoint_navigator#16]
hey thanks for release such a great package !
when i  do the installation step by step to 
```
wstool update
```
which after  `wstool set --git waypoint_navigator git@github.com:ethz-asl/waypoint_navigator.git -y`
and shows some error like this : 
```
[waypoint_navigator] Fetching git@github.com:ethz-asl/waypoint_navigator.git (version None) to /home/max/ethz_ws/src/waypoint_navigator
Cloning into '/home/max/ethz_ws/src/waypoint_navigator'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Exception caught during install: Error processing 'waypoint_navigator' : [waypoint_navigator] Checkout of git@github.com:ethz-asl/waypoint_navigator.git version None into /home/max/ethz_ws/src/waypoint_navigator failed.

ERROR in config: Error processing 'waypoint_navigator' : [waypoint_navigator] Checkout of git@github.com:ethz-asl/waypoint_navigator.git version None into /home/max/ethz_ws/src/waypoint_navigator failed.
```
and i already try to add "sudo" ,manually copy SSH code by github wedsite, still cannot solved this

Can anybody give me some suggestion? 

thx again

**Comment by UestcVan** [comment]
Hi have you solved this problem? I have the same problem.

**Comment by maxwu8416** [comment]
Yeah u have to set the ssh key between ur pc and ur  github account cause u clone the git from ssh link

**Comment by UestcVan** [comment]
I may not understand you too much. Can you describe it in more detail? For example, what parts should be modified to make this part successful.

**Comment by maxwu8416** [comment]
The problem is not came from the installation step 
It came error because u have to set the SSH Key with ur github account 
Just search “how to set the ssh key with github” when u finish the ssh setting I think the error will be solved

**Comment by UestcVan** [comment]
thank you for your help
