### ISSUE TITLE
mav_sim.launch error while rosrun

### ISSUE THREAD

**Issue by marselomeri** [ethz-asl/waypoint_navigator#17]
I successfully build waypoint_navigator , but when I try to run the examples shown , I have this error as shown in the pics: 
![Screenshot from 2019-03-25 13-39-44](https://user-images.githubusercontent.com/41054948/54923036-ac911500-4f09-11e9-8a76-cc318325fe2c.png)
![Screenshot from 2019-03-25 13-40-00](https://user-images.githubusercontent.com/41054948/54923043-b286f600-4f09-11e9-8990-6c4dcfe4e661.png)

**Comment by sprakashdash** [comment]
How did you correct it?
