### ISSUE TITLE
Unable to build the waypoint_navigator package 

### ISSUE THREAD

**Issue by yashoza** [ethz-asl/waypoint_navigator#5]
I am trying to follow the instructions on - https://github.com/ethz-asl/waypoint_navigator to build the waypoint_navigator package, but am getting this build error as seen in the pic. Any help is appreciated. TIA

![3](https://user-images.githubusercontent.com/10346544/44329119-99790c80-a431-11e8-8189-3f53c5619b5c.png)

**Comment by rikba** [comment]
Hi Yashoza

the underlying [mav_trajectory_generation](https://github.com/ethz-asl/mav_trajectory_generation) has changed recently. Either checkout an older branch of mav_trajectory_generation or this needs to be fixed internally in waypoint_navigator. @marija-p
